### ISSUE TITLE
ymlエラー

### ISSUE THREAD

**Issue by hane-jp** [amishiro/AmiTemplate-PHP#121]
```
[16:37:03] Starting 'css'...
[16:37:03] Starting 'doc'...
[16:37:03] Finished 'doc' after 4.18 ms
[16:37:05] config file: C:\***\***\AmiTemplate-PHP\styleguide-config\aigis_config.yml
[Info] Config File: C:\***\***\AmiTemplate-PHP\styleguide-config\aigis_config.yml
[Info] Start: Generate Styleguide
Unhandled rejection Error: Error: ENOTEMPTY: directory not empty, rmdir 'C:\***\***\AmiTemplate-PHP\public\_styleguide\category\common\header'
    at C:\***\***\AmiTemplate-PHP\node_modules\node-aigis\lib\Aigis.js:103:17
    at tryCatcher (C:\***\***\AmiTemplate-PHP\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\***\***\AmiTemplate-PHP\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\***\***\AmiTemplate-PHP\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (C:\***\***\AmiTemplate-PHP\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (C:\***\***\AmiTemplate-PHP\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\***\***\AmiTemplate-PHP\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\***\***\AmiTemplate-PHP\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EPERM
    at _errnoException (util.js:1026:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1360:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amiTemplate-PHP@ gulp: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amiTemplate-PHP@ gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by hane-jp** [comment]
**Qiitaの記事**

https://qiita.com/matsuoshi/items/2df5258741bc62f30ca7

解決には至っていないがMacでは起きない事象でWindows固有っぽい？？

**Comment by amishiro** [comment]
@hane-jp 

試しに、連絡頂いた内容を反映してみた。以下ブランチでエラーは解除されるだろうか？
↓
https://github.com/amishiro/AmiTemplate-PHP/tree/yml%E3%82%A8%E3%83%A9%E3%83%BC-%23121

---

テスト方法
↓
１）nodeモジュールを削除
２）```$ npm i```
３）```$ npm run gulp doc``` スタイルガイド生成

**Comment by hane-jp** [comment]
@amishiro 
エラー出ないです！

---

D:\vagrant\AmiTemplate-PHP>npm run gulp doc

> amiTemplate-PHP@ gulp D:\vagrant\AmiTemplate-PHP
> gulp "doc"

[09:59:27] Using gulpfile D:\vagrant\AmiTemplate-PHP\gulpfile.js
[09:59:27] Starting 'doc'...
[09:59:27] Finished 'doc' after 12 ms
[09:59:27] config file: D:\vagrant\AmiTemplate-PHP\styleguide-config\aigis_config.yml
[Info] Config File: D:\vagrant\AmiTemplate-PHP\styleguide-config\aigis_config.yml
[Info] Start: Generate Styleguide
[Info] Output: D:\vagrant\AmiTemplate-PHP\public\_styleguide
[Info] Finish: Generate Styleguide

D:\vagrant\AmiTemplate-PHP>

**Comment by amishiro** [comment]
yhaa!!!
↓
リリースします。

**Comment by amishiro** [comment]
@hane-jp 

リリースしました。
↓
https://github.com/amishiro/AmiTemplate-PHP/releases/tag/v2.0.12
