### ISSUE TITLE
[gulp]windows-64bit node-sass error

### ISSUE THREAD

**Issue by hane-jp** [amishiro/AmiTemplate-PHP#72]
D:\xxx\xxx\xxx\xxx>gulp
D:\xxx\xxx\xxx\xxx\node_modules\node-sass\lib\binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding D:\xxx\xxx\xxx\xxx\node_modules\node-sass\vendor\win32-x64-57\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (D:\xxx\xxx\xxx\xxx\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (D:\xxx\xxx\xxx\xxx\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\xxx\xxx\xxx\xxx\node_modules\gulp-sass\index.js:187:21)

**Comment by amishiro** [comment]
了解。
windows用にpackage.jsonを書き換えます。

```
"preinstall": "npm install -g gulp@3.9.1",
↓
"preinstall": "npm install -g gulp@3.9.1 node-sass@4.5.3",
```

該当のサイトのdevelopを落としてください。

**Comment by amishiro** [comment]
AmiTemplateには別途反映予定。

時間が・・・(TдT)

**Comment by amishiro** [comment]
> ノードSassはあなたの現在の環境のためのバインディングを見つけることができませんでした：Windows 64ビットwith Node.js 8.x

> 以下の環境でバインディングが見つかりました：

> Windows 64ビット（Node.js 6.x）
> これは通常、npm installを実行してから環境が変更されたために発生します。
> npmを実行すると、現在の環境のバインディングを構築するためのnode-sass --forceが再構築されます。

つまり

`node-sass --force`で解決しましたか？

**Comment by amishiro** [comment]
npm rebuild node-sass --forceで解決するとことで、package.jsonをいじって、npm rebuild node-sass --forceをnpm i 後に自動実行するように変更します。
↓
```
	"scripts": {
		"install": "npm rebuild node-sass --force"
	},
```

AmiTemplate _v_2に反映後クローズ予定。

**Comment by amishiro** [comment]
AmiTemplate _v_2に反映したので、クローズ。
