### ISSUE TITLE
現在発生しているnode-gypエラーの内容

### ISSUE THREAD

**Issue by hane-jp** [amishiro/AmiTemplate-PHP#92]
`このソリューション内のプロジェクトを 1 度に 1 つずつビルドします。並行ビルドを有効にするには、"/m" スイッチを追加して ください。
2017/10/30 17:24:36 にビルドを開始しました。
ノード 1 上のプロジェクト "C:\Vagrant\AmiTemplate-PHP\node_modules\node-sass\build\binding.sln" (既定のターゲット)。
ValidateSolutionConfiguration:
  ソリューション構成 "Release|x64" をビルドしています。
MSBUILD : error MSB3428: Visual C++ コンポーネント "VCBuild.exe" を読み込めませんでした。この問題を解決するには、次の いずれかを行ってください。 1) .NET Framework 2
.0 SDK インストールする。 2) Microsoft Visual Studio 2005 をインストールする。 3) その他の場所にインストールされている場合、コンポーネントの場所をシステム パスに追加する。 [C:\Vagr
ant\AmiTemplate-PHP\node_modules\node-sass\build\binding.sln]
プロジェクト "C:\Vagrant\AmiTemplate-PHP\node_modules\node-sass\build\binding.sln" (既定のターゲット) のビルドが終了しました -- 失敗。

ビルドに失敗しました。

"C:\Vagrant\AmiTemplate-PHP\node_modules\node-sass\build\binding.sln" (既定のターゲット) (1) ->
(_src_\libsass ターゲット) ->
  MSBUILD : error MSB3428: Visual C++ コンポーネント "VCBuild.exe" を読み込めませんでした。この問題を解決するには、次 のいずれかを行ってください。 1) .NET Framework
 2.0 SDK インストールする。 2) Microsoft Visual Studio 2005 をインストールする。 3) その他の場所にインストールされている場合、コンポーネントの場所をシステム パスに追加する。 [C:\Va
grant\AmiTemplate-PHP\node_modules\node-sass\build\binding.sln]

    0 個の警告
    1 エラー

経過時間 00:00:02.17
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Vagrant\AmiTemplate-PHP\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files (x86)\\Nodist\\v-x64\\8.6.0\\node.exe" "C:\\Vagrant\\AmiTemplate-PHP\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Vagrant\AmiTemplate-PHP\node_modules\node-sass
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
node-sass@4.5.3 C:\Vagrant\AmiTemplate-PHP\node_modules\node-sass
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 114 packages in 120.844s`

**Comment by hane-jp** [comment]
Visual C++ 2015 Build Tools　をインストール

http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by amishiro** [comment]
保存版！
